#################### Metrics ###############################

Metrics/LineLength:
  Description: 'Limit lines to 100 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  StyleGuide: '#short-methods'
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Enabled: true
#################### Style ###############################


Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: '#consistent-string-literals'
  Enabled: true
  EnforcedStyle: single_quotes, double_quotes


