#################### Metrics ###############################

Metrics/LineLength:
  Description: 'Limit lines to 100 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: true
  Max: 100

#################### Style ###############################


Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: '#consistent-string-literals'
  Enabled: false
  EnforcedStyle: "double_quotes"


