language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.10
env:
  - DB=postgresql
before_install:
  - gem update --system
  - gem install bundler
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec spec/

