default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: flashcards_development

test:
  <<: *default
  database: flashcards_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
